// Generated by https://quicktype.io

export interface FloorsResponse {
    data:    Floors[];
    success?: boolean;
    message?: string;
    status?:  string;
}

export interface Floors {
    idPiso:         number;
    aforoMaximo:    number;
    idSucursal:     number;
    nombre:         string;
    numeroPiso:     number;
    nombreSucursal: string;
}
