// Generated by https://quicktype.io

export interface RoomsPerFloorResponse {
    data:    Roomr[];
    success?: boolean;
    message?: string;
    status?:  string;
}

export interface Roomr {
    idSala:        number;
    aforoMax:      number;
    dominioEstado: string;
    idPiso:        number;
    nombre:        string;
    nombrePiso:    string;
}
