// Generated by https://quicktype.io

export interface workSpacesPerFloorResponse {
    data:    workSpaceW[];
    success?: boolean;
    message?: string;
    status?:  string;
}

export interface workSpaceW {
    idPuestoTrabajo: number;
    dominioEstado:   string;
    dominioTipo:     string;
    idPiso:          number;
    nombre:          string;
    nombrePiso:      string;
}
