export interface RoomsResponse {
    data:    Room[];
    success: boolean;
    message: string;
    status:  string;
}

export interface Room {
    idSala:        number;
    aforoMax:      number;
    dominioEstado: DominioEstado;
    idPiso:        number;
    nombre:        string;
}

export enum DominioEstado {
    A = "A",
}

export interface FloorResponse {
    data:    Floor[];
    success: boolean;
    message: string;
    status:  string;
}

export interface Floor {
    idPiso:      number;
    aforoMaximo: number;
    idSucursal:  number;
    nombre:      string;
    numeroPiso:  number;
}

// Generated by https://quicktype.io

export interface Schedule {
    idHorario:      number;
    idSucursal:     number;
    numeroHoras:    number;
    nombre:         string;
    horaFin:        string;
    horaInicio:     string;
    nombreSucursal: NombreSucursal;
}

export enum NombreSucursal {
    TorreSigma = "TORRE SIGMA",
}
