export interface RoomsResponse {
    data:    Room[];
    success: boolean;
    message: string;
    status:  string;
}

export interface Room {
    idSala:        number;
    aforoMax:      number;
    dominioEstado: DominioEstado;
    idPiso:        number;
    nombre:        string;
}

export enum DominioEstado {
    A = "A",
}
// Generated by https://quicktype.io

export interface AdminsResponse {
    data:    Administrador[];
    success: boolean;
    message: string;
    status:  string;
}

export interface Administrador {
    idAdministrador: number;
    email:           string;
    idSucursal:      number;
}
