
export interface FloorResponse {
    data:    Floor[];
    success: boolean;
    message: string;
    status:  string;
}

export interface Floor {
    idPiso:      number;
    aforoMaximo: number;
    idSucursal:  number;
    nombre:      string;
    numeroPiso:  number;
    nombreSucursal: string;
}

// Generated by https://quicktype.io

export interface SucursalResponse {
    data:    Sucursal[];
    success: boolean;
    message: string;
    status:  string;
}

export interface Sucursal {
    idSucursal:    number;
    aforoMaximo:   number;
    direccion:     string;
    nit:           string;
    nombre:        string;
    nombreEmpresa: string;
}

