export interface ReservationResponse {
    data:    DatesReservation[];
    success?: boolean;
    message?: string;
    status?:  string;
}

export interface DatesReservation {
    numeroReserva:       number;
    dia:                 string;
    horaInicio:          string;
    horaFin:             string;
    dominioEstado:       string;
    dominioTipoVehiculo: string;
    placa:               string;
    nombreSala:          string;
    nombrePuesTrabajo:   string;
    numeroAsistentes:    number;
    idPiso:              number;
    idSala:              number;   
    idPuestoTrabajo:     number;
    numeroPiso:          number;  
}
export class DatesReservationClass {
    numeroReserva!:       number;
    dia!:                 string;
    horaInicio!:          string;
    horaFin!:             string;
    dominioEstado!:       string;
    dominioTipoVehiculo!: string;
    placa!:               string;
    nombreSala!:          string;
    nombrePuesTrabajo!:   string;
    numeroAsistentes!:    number;
    idPiso!:              number;
    idSala!:              number;   
    idPuestoTrabajo!:     number; 
    numeroPiso!:          number;
    
    constructor(){} 
}

// Generated by https://quicktype.io

export interface UsersBlockResponse {
    data:    DataUsersBlock[];
    success?: boolean;
    message?: string;
    status?:  string;
}

export interface DataUsersBlock {
    idBloqueado:    number;
    email:          string;
    idSucursal:     number;
    nombreSucursal: string;
    bloqueadoHasta: string;
    remainingDays:  number;
}

